export const primitives = {
  color: {
    brand: {
      "1": {
        100: "#CEBAFF",
        300: "#A888F7",
        400: "#9069F0",
        500: "#8352FF",
        600: "#6941CC",
      },
      "2": {
        100: "#F6D9F6",
        300: "#EBADEC",
        400: "#E79DE8",
        500: "#CC5ACA",
        600: "#BF4CBD",
      },
      "3": {
        100: "#E0E0FF",
        300: "#7AB4FA",
        400: "#569BF0",
        500: "#3888EB",
        600: "#2674D4",
      },
    },
    primary: {
      100: "#4A4874",
      200: "#6D6D92",
      300: "#9292AA",
      400: "#B5B5C5",
      500: "#CFCFDD",
      600: "#EBEBF2",
    },
    secondary: {
      1: "#2E2D49",
      2: "#363455",
      3: "#D0D0E5",
      4: "#1F1E2E",
      5: "#2E2D49",
      6: "#9292AA",
      7: "#26253C",
      8: "#1F1E2E",
      9: "#D0D0E5",
      10: "#3D61BF",
      11: "#E06B49",
      12: "#7D4ADC",
      13: "#FFFFFF",
      14: "#000000",
      15: "#232828",
      16: "#83B71A",
      17: "#FFFFFF",
      18: "#0B1010",
      19: "#2E2D49",
      20: "#363555",
      21: "#FFFFFF",
      22: "#26253C",
      23: "#F53B5D",
    },
    accent: {
      error: { 500: "#F53B5D", 600: "#C93E58" },
      info: { 500: "#36BCF2", 600: "#3792B6" },
      success: { 500: "#47DA9C", 600: "#2D9F6F" },
      warning: { 500: "#E5DD38", 600: "#BFB829" },
    },
    white: "#FFFFFF",
    black: "#000000",
  },
  typography: {
    family: {
      general: "Arial",
      comments: "Monaco",
      banner: "Arial",
    },
    weight: {
      regular: "Regular",
      bold: "Bold",
      underline: "Regular",
    },
    size: {
      xs: 8,
      sm: 10,
      md: 12,
      lg: 14,
      "lg+": 16,
      xl: 18,
      "2xl": 20,
      "3xl": 24,
      "4xl": 30,
      "5xl": 36,
    },
    lineHeight: {
      xs: 9,
      sm: 11,
      md: 14,
      lg: 16,
      xl: 18,
      "2xl": 20,
      "3xl": 21,
      "4xl": 23,
      "5xl": 28,
      "6xl": 34,
      "7xl": 35,
      "8xl": 42,
    },
  },
  radius: {
    button: { sm: 20, md: 20, lg: 30, iconButtonNew: 20, presetButton: 8, newButtonFilled: 4 },
    cards: {
      gameCard: 6,
      cardItem: 16,
      coinCard: 20,
      logoProvider: 8,
      logoPaymentMethod: 8,
      sportCard: 6,
      blogCard: 6,
      lootbox: 16,
      loyaltyCard: 6,
    },
    inputs: { old: 4, new: 8, otpCodeItem: 8 },
    tab: { categoryV2: 24, sectionV2: 20, newTabComponent: 20 },
    widget: { widget1: 6, widget2: 8, widgetV3: 16, bentoWidget: 16 },
    popup: { descSkin1: 6, descSkin2: 16, mobSkin1: 6, mobSkin2: 12 },
    background: { general: 16, footer: 16 },
    sidebar: 16,
    menu: { mobileNavigation: 16, gameNavDeskIframe: 16, gameNavMobileIframe: 40 },
    zero: 0,
  },
} as const;

export const aliases = {
  "letterColor.text.dark": "{Primary.100}",
  "letterColor.text.gray": "{Primary.200}",
  "letterColor.special.link": "{Brand Color.1.500}",
  "letterColor.special.warning": "{Accent Color.Warning.500}",
  "letterColor.brand.brandColor1_600": "{Brand Color.1.600}",
  "letterColor.brand.brandColor1_500": "{Brand Color.1.500}",
  "letterColor.brand.brandColor1_400": "{Brand Color.1.400}",
  "letterColor.brand.brandColor1_300": "{Brand Color.1.300}",
} as const;

export const semantic = {
  surface: {
    background: primitives.color.secondary[4],
    header: primitives.color.secondary[1],
    subheader: primitives.color.secondary[2],
    card: primitives.color.secondary[5],
    footer: primitives.color.secondary[6],
    categoryMobileNav: primitives.color.secondary[7],
    mobileNavBackground: primitives.color.secondary[8],
    mobileNavIconText: primitives.color.secondary[9],
  },
  text: {
    default: primitives.color.white,
    dark: primitives.color.primary[100],
    gray: primitives.color.primary[200],
    muted: primitives.color.secondary[3],
  },
  status: {
    error: primitives.color.accent.error[500],
    success: primitives.color.accent.success[500],
    warning: primitives.color.accent.warning[500],
    info: primitives.color.accent.info[500],
  },
  action: {
    primary: primitives.color.brand["1"][500],
    primaryHover: primitives.color.brand["1"][600],
    link: primitives.color.brand["1"][500],
  },
} as const;

export const cssVariables = {
  "--color-brand-1-100": primitives.color.brand["1"][100],
  "--color-brand-1-300": primitives.color.brand["1"][300],
  "--color-brand-1-400": primitives.color.brand["1"][400],
  "--color-brand-1-500": primitives.color.brand["1"][500],
  "--color-brand-1-600": primitives.color.brand["1"][600],
  "--color-brand-2-100": primitives.color.brand["2"][100],
  "--color-brand-2-300": primitives.color.brand["2"][300],
  "--color-brand-2-400": primitives.color.brand["2"][400],
  "--color-brand-2-500": primitives.color.brand["2"][500],
  "--color-brand-2-600": primitives.color.brand["2"][600],
  "--color-brand-3-100": primitives.color.brand["3"][100],
  "--color-brand-3-300": primitives.color.brand["3"][300],
  "--color-brand-3-400": primitives.color.brand["3"][400],
  "--color-brand-3-500": primitives.color.brand["3"][500],
  "--color-brand-3-600": primitives.color.brand["3"][600],
  "--color-primary-100": primitives.color.primary[100],
  "--color-primary-200": primitives.color.primary[200],
  "--color-primary-300": primitives.color.primary[300],
  "--color-primary-400": primitives.color.primary[400],
  "--color-primary-500": primitives.color.primary[500],
  "--color-primary-600": primitives.color.primary[600],
  "--color-secondary-1": primitives.color.secondary[1],
  "--color-secondary-2": primitives.color.secondary[2],
  "--color-secondary-3": primitives.color.secondary[3],
  "--color-secondary-4": primitives.color.secondary[4],
  "--color-secondary-5": primitives.color.secondary[5],
  "--color-secondary-6": primitives.color.secondary[6],
  "--color-secondary-7": primitives.color.secondary[7],
  "--color-secondary-8": primitives.color.secondary[8],
  "--color-secondary-9": primitives.color.secondary[9],
  "--color-accent-error-500": primitives.color.accent.error[500],
  "--color-accent-success-500": primitives.color.accent.success[500],
  "--color-accent-warning-500": primitives.color.accent.warning[500],
  "--color-accent-info-500": primitives.color.accent.info[500],
  "--radius-button-sm": `${primitives.radius.button.sm}px`,
  "--radius-button-md": `${primitives.radius.button.md}px`,
  "--radius-button-lg": `${primitives.radius.button.lg}px`,
  "--radius-card-game": `${primitives.radius.cards.gameCard}px`,
  "--radius-card-item": `${primitives.radius.cards.cardItem}px`,
  "--radius-card-coin": `${primitives.radius.cards.coinCard}px`,
  "--radius-input-new": `${primitives.radius.inputs.new}px`,
  "--radius-tab-category-v2": `${primitives.radius.tab.categoryV2}px`,
  "--radius-tab-section-v2": `${primitives.radius.tab.sectionV2}px`,
  "--radius-widget-v3": `${primitives.radius.widget.widgetV3}px`,
  "--radius-widget-bento": `${primitives.radius.widget.bentoWidget}px`,
  "--font-family-general": primitives.typography.family.general,
} as const;

export const tailwindTokens = {
  colors: {
    brand: {
      100: "var(--color-brand-1-100)",
      300: "var(--color-brand-1-300)",
      400: "var(--color-brand-1-400)",
      500: "var(--color-brand-1-500)",
      600: "var(--color-brand-1-600)",
    },
    pink: {
      100: "var(--color-brand-2-100)",
      300: "var(--color-brand-2-300)",
      400: "var(--color-brand-2-400)",
      500: "var(--color-brand-2-500)",
      600: "var(--color-brand-2-600)",
    },
    blue: {
      100: "var(--color-brand-3-100)",
      300: "var(--color-brand-3-300)",
      400: "var(--color-brand-3-400)",
      500: "var(--color-brand-3-500)",
      600: "var(--color-brand-3-600)",
    },
    primary: {
      100: "var(--color-primary-100)",
      200: "var(--color-primary-200)",
      300: "var(--color-primary-300)",
      400: "var(--color-primary-400)",
      500: "var(--color-primary-500)",
      600: "var(--color-primary-600)",
    },
    surface: {
      bg: "var(--color-secondary-4)",
      card: "var(--color-secondary-5)",
      sub: "var(--color-secondary-2)",
      nav: "var(--color-secondary-7)",
      header: "var(--color-secondary-1)",
    },
    secondary: {
      3: "var(--color-secondary-3)",
      20: "var(--color-secondary-20)",
    },
    error: { 500: "var(--color-accent-error-500)" },
    success: { 500: "var(--color-accent-success-500)" },
    warning: { 500: "var(--color-accent-warning-500)" },
    info: { 500: "var(--color-accent-info-500)" },
  },
  borderRadius: {
    "btn-sm": "var(--radius-button-sm)",
    "btn-md": "var(--radius-button-md)",
    "btn-lg": "var(--radius-button-lg)",
    card: "var(--radius-card-game)",
    "card-lg": "var(--radius-card-item)",
    "card-coin": "var(--radius-card-coin)",
    input: "var(--radius-input-new)",
    tab: "var(--radius-tab-section-v2)",
    "tab-category": "var(--radius-tab-category-v2)",
    widget: "var(--radius-widget-v3)",
    "widget-bento": "var(--radius-widget-bento)",
  },
} as const;
